[package]
name = "cean"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serenity = { version = "0.12.4", features = ["client", "gateway"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
env_logger = "0.11.5"
